 [database]
 #开发
 #host = 10.11.14.182
 #测试
 host = 10.11.15.195
 port = 5432
 user = bdh
 pswd = Tge16ZA9on
 dbname = bdh

 [message]
 # 开发
 #address = 10.11.14.27:9876,10.11.14.28:9876
 #测试
 address = 10.11.15.186:9876;10.11.15.187:9876
 producer = SmartShifeiProducer
 consumer = SmartShifeiConsumer
 topic = bdh_ai_message
 tags = seedling
 log = bdh_ai_message.log

 [push_message]
 # 开发
 #address = 10.11.14.27:9876,10.11.14.28:9876
 #测试
 address = 10.11.15.186:9876;10.11.15.187:9876
 producer = SmartShifeiProducer
 consumer = SmartShifeiConsumer
 topic = bdh_ai_result
 tags = seedling
 log = bdh_ai_result.log

 [seedling]
 upload_url = http://10.11.14.214:31111/file/obs/upload?keyCode=6521e74c5ca64ec886e7d299df453873
 res_path = /opt/image/new_UAV/